### ISSUE TITLE
mixed up addresses when replying to all in a new window

### ISSUE THREAD

**Issue by ervit** [protz/GMail-Conversation-View#975] opened 2015-06-19 10:49 UTC
After updating TB to 38 and TB Conversations to 2.9.0, I noticed that when I "reply all" in a new window, then email addresses are mixed up. For example, say there are 5 participants including me, with their respective email addresses: A (A), B (B), C (C), D (D) and Me (Me). Then in the address fields (To and CC) addresses would be shuffled between people: A (B), B (Me), C (D), D (A) (shuffle order is purely for illustration, I have not looked at any pattern there). The worst thing is that TB then harvests the wrong associations into its collected addresses and offers them in address autocomplete, which can create a lot of problems.

**Comment by msprotz** [comment] 2015-06-20 05:07
Screenshot?

**Comment by protz** [comment] 2015-06-20 05:08
Can you post a screenshot?

**Comment by ervit** [comment] 2015-06-20 19:02
Update: I'm having the issue in a slightly different format in the Quick reply window: it just replies to the wrong email that is also in the same folder (wrong email's text is in the reply window and the To and From addresses are undoubtedly from there). See attached screenshot. I can't show a screenshot for the previous message because all those email addresses are confidential.
![screenshot 42](https://cloud.githubusercontent.com/assets/12965681/8268772/e340082a-1797-11e5-97cd-e276de2b41e1.png)

**Comment by ervit** [comment] 2015-06-20 20:47
I've just noticed that some of my initial text was interpreted as code syntax. I've edited - the capital letters in parentheses represent the email addresses of the respective people.

**Comment by msprotz** [comment] 2015-06-21 04:06
Well perhaps the email you're replying to has a Reply-To header?

**Comment by ervit** [comment] 2015-06-22 05:16
I'm more than certain that's not the case (because a person is unlikely to have Elance's no-reply address in Reply-to field, especially when I have conversed with them before). Besides, as I mentioned above, that wrong email is in the body of the reply and the email addresses are from that wrong email. The screenshot above shows that also my own email identity is wrong (using the account from the substitute message rather than the original).

**Comment by ervit** [comment] 2015-06-22 12:22
I didn't have any problems today. Will keep an eye on this in case it happens again.

**Comment by Bary** [comment] 2015-06-23 09:38
I can confirm the same situation :( More recipient are problem (mixed up addresses). Maybe the problem is when there is anyone without a name for email address (for ex support@xy.com and not Support XY, support@xy.com). Because I allready aswered this email (Reply All in new window is OK, my problem was clicking the button Reply All below email body) all is OK now :( It repaired itself in this conversation, but first Reply all was buggy.

**Comment by Bary** [comment] 2015-06-25 06:13
So it happend again. Now email comes. I am the recipient + one person. If I click "Reply All" button bellow the email body, I reply sender + one person but that person has MY EMAIL! So I reply sender and myself (even I see name of that person) If I click "in new window" bellow "Reply All" button all is OK and emails are OK.

**Comment by protz** [comment] 2015-06-28 19:41
Can you try to forward this message to me (using Message > Forward As > Attachment in the menus, otherwise it won't work), then tell me which was your email address among these? I'll try to reproduce.

**Comment by Redart98** [comment] 2015-06-29 09:08
Sent you an e-mail

**Comment by Bary** [comment] 2015-07-07 09:01
I am sorry I had a vacation (sorry for a late answer) but original email is deleted :(

**Comment by Redart98** [comment] 2015-07-07 09:03
Here it is

2015-07-07 12:01 GMT+03:00 Bary <notifications@github.com>:

> I am sorry I had a vacation (sorry for a late answer) but original email
> is deleted :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/protz/GMail-Conversation-View/issues/975#issuecomment-119130483>
> .
>



-- 
С уважением, Боженов Артем

**Comment by Redart98** [comment] 2015-07-07 09:07
Original mail was directed to me (Artem Bozhenov <
abozhenov@msk.local.domain.ru>) and Andrey Arkhipov <
AArkhipov@local.domainprime.com>. Reply was sent to <
help@local.domainprime.com> (author of original mail), and to me (with name
changed to Help Desk local.domain). Andrey Arkhipov went missing from the
list.

2015-07-07 12:03 GMT+03:00 Артём Боженов <bozhenov@gmail.com>:

> Here it is
>
> 2015-07-07 12:01 GMT+03:00 Bary <notifications@github.com>:
>
>> I am sorry I had a vacation (sorry for a late answer) but original email
>> is deleted :(
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/protz/GMail-Conversation-View/issues/975#issuecomment-119130483>
>> .
>>
>
>
>
> --
> С уважением, Боженов Артем
>



-- 
С уважением, Боженов Артем

**Comment by Redart98** [comment] 2015-07-07 09:24
Here is another example:
1. I've sent an e-mail to ts@local.domainprime.com (it's a support group)
and a.arkhipov@msk.local.domain.ru
2. Received reply from DNemtcova@local.domainprime.com, targeted to me,
ts@local.domainprime.com and a.arkhipov@msk.local.domain.ru
3. Replied to it. ts@local.domainprime.com went missing. Instead of it mail
was cc'ed back to me.

2015-07-07 12:07 GMT+03:00 Артём Боженов <bozhenov@gmail.com>:

> Original mail was directed to me (Artem Bozhenov <
> abozhenov@msk.local.domain.ru>) and Andrey Arkhipov <
> AArkhipov@local.domainprime.com>. Reply was sent to <
> help@local.domainprime.com> (author of original mail), and to me (with
> name changed to Help Desk local.domain). Andrey Arkhipov went missing from
> the list.
>
> 2015-07-07 12:03 GMT+03:00 Артём Боженов <bozhenov@gmail.com>:
>
>> Here it is
>>
>> 2015-07-07 12:01 GMT+03:00 Bary <notifications@github.com>:
>>
>>> I am sorry I had a vacation (sorry for a late answer) but original email
>>> is deleted :(
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/protz/GMail-Conversation-View/issues/975#issuecomment-119130483>
>>> .
>>>
>>
>>
>>
>> --
>> С уважением, Боженов Артем
>>
>
>
>
> --
> С уважением, Боженов Артем
>



-- 
С уважением, Боженов Артем

**Comment by Notmarrco** [comment] 2015-07-23 12:55
@Redart98 Thk you very much ! is there a simple way for me to use this patch ? this bug is very annoying :)

**Comment by Redart98** [comment] 2015-07-23 13:03
Here is patched xpi:
http://1drv.ms/1OzBpKp

**Comment by Notmarrco** [comment] 2015-07-30 16:08
thks a lot, i've been using it for 5 days without issue yet :)

**Comment by protz** [comment] 2015-08-08 17:02
Thanks to everyone. I'm back from vacation, so I'm closing this (since the fix has been merged). I'll submit a new version to AMO this weekend. Apologies for the delay.

Thanks again for the debugging / bugfixing!

Jonathan

**Closed by protz** 2015-08-08 17:02 UTC
Labels: bug, investigate
